import { NextResponse } from 'next/server';

export async function GET() {
  try {
    // In production, this would query Prisma for leads generated by the AAC Enterprise Portal.
    // We mock the data here to visualize the B2B pipeline the user requested.
    const pipelineData = [
      { id: 'LD-8492', company: 'Acme Corp', seats: 12500, status: 'Negotiating', acv: '$1,350,000', lastTouch: '2 hours ago' },
      { id: 'LD-8493', company: 'Global Health', seats: 84000, status: 'Demo Requested', acv: '$5,190,000', lastTouch: '4 hours ago' },
      { id: 'LD-8494', company: 'Starlight Tech', seats: 200, status: 'Checkout Abandoned', acv: '$178,800', lastTouch: '1 day ago' },
      { id: 'LD-8495', company: 'Nexus Logistics', seats: 4500, status: 'Contract Sent', acv: '$582,000', lastTouch: '3 days ago' },
      { id: 'LD-8496', company: 'Apex Financial', seats: 110000, status: 'Closed Won', acv: '$6,750,000', lastTouch: '1 week ago' },
    ];

    const totalPipelineValue = pipelineData.reduce((acc, lead) => {
      const val = parseInt(lead.acv.replace(/[^0-9]/g, ''), 10);
      return acc + val;
    }, 0);

    return NextResponse.json({ 
      success: true, 
      totalPipelineValue,
      leads: pipelineData 
    });
  } catch (error) {
    console.error('Pipeline Fetch Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
